version: '3.9'
services:
  postgresql-dev:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  api-dev:
    build:
      context: .
      args:
        NODE_ENV: stagging
    entrypoint: ["/bin/sh", "/app/start-dev.sh"]
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.stage
    depends_on:
      - postgresql-dev
    command: ["/app/wait-for-it.sh", "postgresql-dev:5432"]
