version: '3.9'
services:
  postgresql-prod:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_PRODUCTION}
  api-prod:
    build:
      context: .
      args:
        NODE_ENV: production
    entrypoint: ["/bin/sh", "/app/start-prod.sh"]
    ports:
      - "8080:8080"
    environment:
      - DIALECT=${DB_CONNECTION}
      - HOST=${DB_HOST_PRODUCTION}
      - USER=${DB_USERNAME}
      - PASSWORD=${DB_PASSWORD}
      - DB=${DB_DATABASE_PRODUCTION}
    depends_on:
      - postgresql-prod
    command: ["/app/wait-for-it.sh", "postgresql-prod:5432"]
    