version: '3.9'
services:
  postgresql-dev:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=aegis
      - POSTGRES_PASSWORD=bismillah
      - POSTGRES_DB=aegis
  api-dev:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - postgresql-dev
    command: ["/app/wait-for-it.sh", "postgresql-dev:5432"]
    entrypoint: ["/bin/sh", "/app/start-dev.sh"]
