# fly.toml app configuration file generated for mangrove on 2023-06-05T08:53:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mangrove"
primary_region = "sin"

[env]
  NODE_ENV = "stage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
